#!/usr/bin/zsh

echo Setting local ip for ROS
unset ip

ifconfig|while read line
do
	[[ $line =~ "([0-9]{1,3}\.){3}([0-9]{2,3}|[2-9])" ]] && ip=($MATCH[*] $ip)
	#echo Matched ip address: $ip
done

cnt=$ip[(I)$ip[-1]]

if [[ $cnt -eq 0 ]]; then 
	echo no address found...defaulting to localhost
	export ROS_IP=localhost
fi

if [[ $cnt -eq 1 ]]; then 
	echo 1 address found...setting ROS_IP to $ip
	export ROS_IP=$ip
fi


if [[ $cnt -gt 1 ]]; then

	select opt in $ip; do
		if [ "$opt" != "" ]; then
			echo $opt done
			export ROS_IP=$opt
			break
		else
			echo bad option $opt
		fi
	done

fi
