#!/usr/bin/zsh

MASTER_CONF=${HOME}/.ros_master.conf

addr=`cat $MASTER_CONF |head -n 1`
echo $addr

if [[ $1 =~ '-[sS]' ]]; then

	unset mip

	#if -e edit...

	cat ${MASTER_CONF}|while read line
	do
		mip=($mip $line)
	done
	NEW_MASTER_ADDR="N - Enter new address"
	mip=($mip $NEW_MASTER_ADDR)


	select opt in $mip; do
		echo $opt  
		if [[ $opt =~ '[0-9]+' ]]; then
			echo $opt done
			addr=$opt
			
			break
		elif [[ $opt =~ $NEW_MASTER_ADDR ]]; then
		

			while read addr
			do

				if [[ $addr =~ "([0-9]{1,3}\.){3}([0-9]{2,3}|[2-9])" ]];
					then 
					echo Selecting $addr
					break
					 
				else 
					echo Invalid address format
					echo "use #.#.#.# where each # is 0-255 (last char can't be 0 or 1)"
					echo address = $addr
				fi
			done

			break	

		else
			echo bad option $opt
		fi
	done
fi	


export ROS_MASTER_URI=http://$addr:11311
echo exporting ROS_MASTER_URI=http://$addr:11311
grep -v "${addr}" $MASTER_CONF > $MASTER_CONF.tmp
echo $addr > $MASTER_CONF
cat $MASTER_CONF.tmp >> $MASTER_CONF
